version: '2'
services:
  web:
    build: .
    command: npm test
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data_test:/data/db
    ports:
      - "27017:27017"